export const ALTER_LOADING = 'ALTER_LOADING';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const UNSET_NOTIFICATION = 'UNSET_NOTIFICATION';
export const UPDATE_ENTITY_FIELD = 'UPDATE_ENTITY_FIELD';
export const UPDATE_ENTITY = 'UPDATE_ENTITY';
